modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="playertabs"
version="${file.jarVersion}"
displayName="Player Tabs"
logoFile="logo.png"
credits="Wolforce,XiaoHuNao"
authors="Wolforce"
description='''
    Adds Tabs to the Player Inventory
'''
[[dependencies.playertabs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
